### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kerochelo** [jinta-shimo02/fuku_cafe#93]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
技術もしっかり取り入れてセレクトショップ検索、カフェ検索できますね！

## 静的コードチェックが入っている
余分な空白行があったりするので、rubbocopのチェックと目視でもチェックをしっかり通しておきましょう。

## 就活において十分な技術力を示せる機能を実装しているか
GoogleMapの非同期自動検索などいい機能がありますね。
下記に修正や追加してほしい部分を挙げたのでご確認ください。

- 時々GoogleMapが表示されない時があるのでエラーハンドリングしましょう
- 登録したデータを用いた機能がほしい（似たような場所を検索するときに他のユーザーにレコメンドするなど）

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
基本的にまとまりがあるようなUIになっていますね！
下記に気になる点を挙げたのでご確認ください。

- TOPページの使い方情報はもう少し詳細まで書いてあげるようにしましょう（mapでの検索方法など）
- ヘッダー情報のポインターを統一しておきましょう（ブランド検索だけ別ポインターになっている）
- ブランド検索はデータが決まっているかと思うので、別の検索方法でもいいかも（検索枠を作ってアートコンプリート機能をつけるなど）
- 登録時はJSのalert使っているので、他の方法で登録したことを伝える情報を表示しましょう
- 詳細ページからもリスト追加できるようにしましょう
- 初期段階ではリストが何もない状態から登録する流れになってしまうので、デフォルトで仮のリストを作られている状態にしましょう
- mapのピンをクリックすると詳細画面に遷移してもよさそうです
- map検索時に場所を指定してそこにピンが立つような機能があってもよさそう（技術的に実装する時間があればでOK）

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by jinta-shimo02** [comment]
カンノ講師、レビューありがとうございました！
レビューいただいた点、issueに切り出しました。
改善していきたいと思います！
本リリースについては、1ヶ月後の 11/5（日）を予定しております。
ご確認お願いいたします！

**Comment by kerochelo** [comment]
@jinta-shimo02 
確認しました！
引き続き頑張っていきましょう:+1:
